name: Setup bundletool
description: Set up a specific version of google/bundletool
author: SWAG
branding:
  icon: code
  color: yellow
inputs:
  path:
    description: Path to install bundletool.jar
    default: bundletool.jar
runs:
  using: docker
  image: docker://ghcr.io/swaglive/bundletool:1.8.0
  args:
  - ${{ inputs.path }}
