name: Setup bundletool
description: Set up a specific version of google/bundletool
author: SWAG
branding:
  icon: code
  color: yellow
inputs:
  version:
    description: bundletool version to install
    default: '1.8.0'
  path:
    description: Path to install bundletool.jar
    default: bundletool.jar
runs:
  using: docker
  image: 'docker://bash'
  entrypoint: wget
  args:
  - -O
  - ${{ inputs.path }}
  - https://github.com/google/bundletool/releases/download/${{ inputs.version }}/bundletool-all-${{ inputs.version }}.jar
