name: Release

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
        # - "1.4.0"
        # - "1.5.0"
        # - "1.6.0"
        # - "1.6.1"
        # - "1.7.0"
        # - "1.7.1"
        - "1.8.0"
        - "1.8.1"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: ls -ahl
    - run: pwd

    - name: Setup - Install bundletool
      uses: ./
      with:
        version: ${{ matrix.version }}
        path: bundletool-all-${{ matrix.version }}.jar

    - name: Check
      run: test -f bundletool-all-${{ matrix.version }}.jar
